---
abstract: 'Modules for handling XML data within the Catmandu framework'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-XML
requires:
  Catmandu: 0.9
  XML::LibXSLT: 1.90
  XML::Struct: 0.18
resources:
  bugtracker: https://github.com/gbv/Catmandu-XML/issues
  homepage: https://github.com/gbv/Catmandu-XML
  repository: https://github.com/gbv/Catmandu-XML.git
version: 0.05
